# Generated by Django 4.2.1 on 2023-09-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_training_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
